/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgpeyaRouteImport } from './routes/agpeya'
import { Route as BibleRouteImport } from './routes/bible'
import { Route as BibleBooksRouteImport } from './routes/bible-books'
import { Route as ChurchControlRouteImport } from './routes/church-control'
import { Route as MyChurchRouteImport } from './routes/my-church'
import { Route as ProfileRouteImport } from './routes/profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgpeyaRoute = AgpeyaRouteImport.update({
  id: '/agpeya',
  path: '/agpeya',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleRoute = BibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleBooksRoute = BibleBooksRouteImport.update({
  id: '/bible-books',
  path: '/bible-books',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchControlRoute = ChurchControlRouteImport.update({
  id: '/church-control',
  path: '/church-control',
  getParentRoute: () => rootRouteImport,
} as any)
const MyChurchRoute = MyChurchRouteImport.update({
  id: '/my-church',
  path: '/my-church',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agpeya': typeof AgpeyaRoute
  '/bible': typeof BibleRoute
  '/bible-books': typeof BibleBooksRoute
  '/church-control': typeof ChurchControlRoute
  '/my-church': typeof MyChurchRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agpeya': typeof AgpeyaRoute
  '/bible': typeof BibleRoute
  '/bible-books': typeof BibleBooksRoute
  '/church-control': typeof ChurchControlRoute
  '/my-church': typeof MyChurchRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agpeya': typeof AgpeyaRoute
  '/bible': typeof BibleRoute
  '/bible-books': typeof BibleBooksRoute
  '/church-control': typeof ChurchControlRoute
  '/my-church': typeof MyChurchRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agpeya'
    | '/bible'
    | '/bible-books'
    | '/church-control'
    | '/my-church'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agpeya'
    | '/bible'
    | '/bible-books'
    | '/church-control'
    | '/my-church'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/agpeya'
    | '/bible'
    | '/bible-books'
    | '/church-control'
    | '/my-church'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgpeyaRoute: typeof AgpeyaRoute
  BibleRoute: typeof BibleRoute
  BibleBooksRoute: typeof BibleBooksRoute
  ChurchControlRoute: typeof ChurchControlRoute
  MyChurchRoute: typeof MyChurchRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agpeya': {
      id: '/agpeya'
      path: '/agpeya'
      fullPath: '/agpeya'
      preLoaderRoute: typeof AgpeyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible-books': {
      id: '/bible-books'
      path: '/bible-books'
      fullPath: '/bible-books'
      preLoaderRoute: typeof BibleBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/church-control': {
      id: '/church-control'
      path: '/church-control'
      fullPath: '/church-control'
      preLoaderRoute: typeof ChurchControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-church': {
      id: '/my-church'
      path: '/my-church'
      fullPath: '/my-church'
      preLoaderRoute: typeof MyChurchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgpeyaRoute: AgpeyaRoute,
  BibleRoute: BibleRoute,
  BibleBooksRoute: BibleBooksRoute,
  ChurchControlRoute: ChurchControlRoute,
  MyChurchRoute: MyChurchRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
